version: '3.3'
services:
  es:
    platform: linux/x86_64
    image: elasticsearch:8.11.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
